-- Insert all mock events data into the events table

-- Fitness Events
INSERT INTO events (id, title, subtitle, category, date, time, location, type, description, details, instructor, duration, max_participants, image, book_url) VALUES
('morning-yoga', 'Morning Yoga', 'Gentle flow to start your day', 'fitness', '18-09-2025', '14:00', 'Parramatta South', 'event', 'Start your day with a peaceful and energizing yoga session. Our morning yoga class focuses on gentle flows and breathing exercises that will help you feel centered and ready to tackle the day ahead.', ARRAY['Suitable for all fitness levels', 'Yoga mats provided', 'Guided breathing exercises', 'Stress relief and relaxation', 'Improve flexibility and strength'], 'Sarah Johnson', '1 hour', 20, '/images/360_F_1527954928_5UPs5ilDSieF6nu9LGfV8J36RtvDgGhF.jpg', '/book/morning-yoga'),

('healthy-living-seminar', 'Healthy Living Seminar', 'Expert speakers on nutrition, exercise, and wellbeing', 'fitness', '09-10-2025', '11:00', 'Parramatta City', 'seminar', 'Join nutrition and fitness experts as they share the latest research and practical tips for maintaining a healthy lifestyle. Learn about balanced nutrition, effective exercise routines, and overall wellbeing strategies.', ARRAY['Expert nutrition advice', 'Exercise demonstrations', 'Healthy recipe samples', 'Q&A with professionals', 'Free health screening'], 'Health & Wellness Team', '3 hours', 50, '/images/360_F_1527954928_5UPs5ilDSieF6nu9LGfV8J36RtvDgGhF.jpg', '/book/healthy-living-seminar'),

-- Counselling Events
('mental-health-workshop', 'Mental Health Workshop', 'Learn coping strategies', 'counselling', '17-09-2025', '10:00', 'Parramatta South', 'workshop', 'Join our comprehensive mental health workshop designed to help you develop effective coping strategies for managing stress, anxiety, and daily challenges. This interactive session will provide you with practical tools and techniques to improve your mental wellbeing.', ARRAY['Learn evidence-based coping strategies', 'Interactive group activities', 'Access to mental health resources', 'Q&A session with mental health professionals', 'Take-home materials and worksheets'], 'Dr Kieran Luken', '2 hours', 25, '/images/istockphoto-1340965910-612x612.jpg', '/book/mental-health-workshop'),

('learning-skills-seminar', 'Learning Skills Seminar', 'Improve your study habits', 'counselling', '18-09-2025', '11:00', 'Bankstown', 'seminar', 'Enhance your academic performance with our comprehensive learning skills seminar. Discover effective study techniques, time management strategies, and memory improvement methods that will help you succeed in your studies.', ARRAY['Effective note-taking techniques', 'Time management strategies', 'Memory improvement methods', 'Exam preparation tips', 'Study group formation guidance'], 'Dr Rhys Tague', '1.5 hours', 30, '/images/Learning-Skill-icon-Graphics-26544562-1-1-580x387.jpg', '/book/learning-skills-seminar'),

('stress-management-guide', 'Stress Management Guide', 'Self-paced reading & worksheets', 'counselling', '01-10-2025', '10:00', 'Online', 'workshop', 'Learn effective strategies to manage stress and anxiety through our comprehensive self-paced program. Includes practical worksheets, exercises, and techniques you can use in daily life.', ARRAY['Downloadable worksheets', 'Self-paced learning modules', 'Practical stress-reduction techniques', 'Expert-designed content', 'Access for 6 months'], 'Dr. Michael Chen', 'Self-paced', 100, '/images/istockphoto-1340965910-612x612.jpg', '/book/stress-management-guide'),

('mindfulness-workshop', 'Mindfulness Workshop', 'Interactive session on mindfulness techniques', 'counselling', '05-10-2025', '13:00', 'Campbelltown', 'workshop', 'Discover the power of mindfulness through guided meditation, breathing exercises, and practical techniques for staying present. This interactive workshop will teach you skills to reduce stress and improve focus.', ARRAY['Guided meditation sessions', 'Learn breathing techniques', 'Mindfulness exercises', 'Take-home practice guides', 'Small group setting'], 'Dr. Emma Williams', '2 hours', 25, '/images/Learning-Skill-icon-Graphics-26544562-1-1-580x387.jpg', '/book/mindfulness-workshop'),

-- Social Network Events
('peer-support-group', 'Peer Support Group', 'Meet other students and share', 'socialnetwork', '19-09-2025', '14:00', 'Penrith', 'event', 'Join fellow students in a supportive environment where you can share experiences, challenges, and successes. This peer support group provides a safe space for open discussion and mutual encouragement.', ARRAY['Safe and confidential environment', 'Share experiences with peers', 'Build lasting friendships', 'Receive emotional support', 'Light refreshments provided'], 'Student Counselors', '1.5 hours', 15, '/images/social-wellbeing-concept-icon.jpg', '/book/peer-support-group'),

('career-fair', 'Career Fair', 'Explore job opportunities', 'socialnetwork', '19-09-2025', '09:00', 'Parramatta City', 'event', 'Connect with top employers and explore exciting career opportunities at our annual career fair. Meet representatives from leading companies, learn about internship programs, and get valuable career advice from industry professionals.', ARRAY['Meet 50+ top employers', 'Internship opportunities', 'Resume review sessions', 'Career counseling', 'Networking opportunities'], 'Career Services Team', '4 hours', 200, '/images/360_F_1527954928_5UPs5ilDSieF6nu9LGfV8J36RtvDgGhF.jpg', '/book/career-fair'),

('social-mixer', 'Social Mixer', 'Meet new people', 'socialnetwork', '20-09-2025', '12:00', 'Penrith', 'event', 'Join our fun and relaxed social mixer to meet new people, make friends, and expand your social network. This event is perfect for students looking to connect with peers and build meaningful relationships.', ARRAY['Ice-breaker activities', 'Group games and challenges', 'Free refreshments', 'Networking opportunities', 'Social media connections'], 'Student Life Team', '2 hours', 50, '/images/social-wellbeing-concept-icon.jpg', '/book/social-mixer');
